### ISSUE TITLE
Add "born on" fact

### ISSUE THREAD

**Issue by tfhartmann** [huit/puppet-harvard#1]
It would be awesome to add @sjoeboo 's awesome fact to the common module!

``` Shell
[root@dm ~]# facter born_on
2009-08-31
```

cc / @hakamadare

**Comment by hakamadare** [comment]
see the original blog post here: http://sjoeboo.github.io/blog/2012/08/07/born-on-dates-for-systems/

in particular, in the comments field i suggest the following alternate implementation that works on non-RedHat systems, but, unfortunately, assumes that `/dev/sda1` is the root partition.  the real fix probably involves inspecting other facts, and that sounds awfully like work :(

``` ruby
Facter.add(:system_birthday) do
  confine :kernel => "Linux"
  setcode do
    Facter::Util::Resolution.exec('date --date="$(tune2fs -l /dev/sda1 | grep created | cut -d\ -f3-)" +%F')
  end
end
```

**Comment by tfhartmann** [comment]
doh. forgot to add tests (fail)

**Comment by tfhartmann** [comment]
Hmm interesting, these generate two different dates..

``` Shell
[root@vagrant facter]# date --date="$(tune2fs -l /dev/sda1 | grep created | cut -d\ -f3-)" +%F
cut: the delimiter must be a single character
Try `cut --help' for more information.
2014-03-20
[root@vagrant facter]# facter born_on
2014-01-16
[root@vagrant facter]# 

```
